#!/system/bin/sh

        
#########
#### CONFIG
#########


##SHARED WITH PITCH_DESKTOP
SELF=pitch

IMGDIR=/sdcard
IMGNAME=debian.img
DISTRIB=stable
##SHARED WITH  PITCH_DESKTOP



busybox=/system/xbin/busybox
MNTDIR=/root
SDCARD0DIR=$(readlink -f /sdcard)
SDCARD1DIR=/storage/sdcard1 
SDCARD0MNTDIR=$MNTDIR/media/android
SDCARD1MNTDIR=$MNTDIR/media/coo


BASEPACKAGES="joe nano openssh-server tightvncserver alsa-tools alsa-utils"
ENVPACKAGE=" i3 suckless-tools openbox zsh openbox mousepad"
EXTENDEDPACKAGES="pandoc markdown lyx scala kate geany rosegarden timidity qjackcontrol ardour openscad"

LOOPNO=254
LOOPDEV=/dev/block/loop$LOOPNO

########
#### Primitives
########

function remountsys {
	mount -o remount,rw /system
}

function mount {
  mknod $LOOPDEV b 7 $LOOPNO
	losetup $LOOPDEV $IMGDIR/$IMGNAME
	$busybox mount -t ext4 -o relatime $LOOPDEV $MNTDIR
	for f in dev dev/pts proc sys ; do $busybox mount -o bind /$f $MNTDIR/$f ; done
	if [ ! -d $SDCARD0MNTDIR ]; then
			mount -o remount,rw /system
		  mkdir -p $SDCARD0MNTDIR
	fi
	if [ ! -d $SDCARD1MNTDIR ]; then
			mount -o remount,rw /system
		  mkdir -p $SDCARD1MNTDIR
	fi
	$busybox mount -o bind $SDCARD0DIR $SDCARD0MNTDIR
	$busybox mount -o bind $SDCARD1DIR $SDCARD1MNTDIR
}
function login {
	cd $MNTDIR
	env -i  USER=root HOME=/root TERM=$TERM PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin chroot . bash -l
}

function install {
	/debootstrap/debootstrap --second-stage
	echo "
deb http://ftp.debian.org/debian $DISTRIB main contrib non-free
deb http://ftp.debian.org/debian $DISTRIB-updates main contrib non-free
deb http://security.debian.org/  $DISTRIB/updates main contrib non-free
deb ftp://ftp.deb-multimedia.org $DISTRIB main non-free
	" > etc/apt/sources.list
	login
	apt-get update
	apt-get install deb-multimedia-keyring
	apt-get update
	apt-get upgrade
	dpkg-reconfigure tzdata
	apt-get install $BASEPACKAGES
	apt-get autoclean
	exit
}
# PS1="(pitch) $PS1"

function backup {
	cd $IMGDIR
  mv debian.img debian.img.minimal
  dd if=/dev/zero of=debian.img bs=1m count=8192
	##SE CONNECTER ICI EN CHROOT SI ON VEUT mkfs.ext4 debian.img
	mkfs.ext2 debian.img
	##SE CONNECTER ICI EN CHROO
		if [ ! -d debian ]; then
		  mkdir -p debian
	fi
	mount -o loop debian.img debian/
		if [ ! -d debianmin ]; then
		  mkdir -p debianmin
	fi
	 $busybox mount -o loop debian.img debian/
	 $busybox mount -o loop debian.img.minimal debianmin/
	umount debian/
	umount debianmin/
	rm -r debian/
	rm -r debianmin/
}

function unmount {
	for f in dev/pts dev proc sys ; do umount $MNTDIR/$f ; done
	umount $MNTDIR
	losetup -d $LOOPDEV
	rm $LOOPDEV
}

function view_part {
	mount ; ls -l /dev/block
}
#######
### Main
#######

if [ $EUID -ne 0 ]
then
	echo "Becoming ROOT!"
	su -c $SELF
	exit 1
fi

OPTIONS="Mount Login Install Backup Umount RemountSysRW Exit"

select opt in $OPTIONS; do
   if [ "$opt" = "Login" ]; then
    login
   elif [ "$opt" = "Mount" ]; then
    mount
   elif [ "$opt" = "Install" ]; then
    install
   elif [ "$opt" = "Backup" ]; then
		backup
   elif [ "$opt" = "Umount" ]; then
    umount
   elif [ "$opt" = "RemountSysRW" ]; then
    remountsys
   elif [ "$opt" = "Exit" ]; then
    echo done
    exit
   else
    clear
    echo bad option
   fi
done

exit 0